stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose up -d
