name: book-lovers

services:
  frontend:
    container_name: book-lovers-frontend
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        API_URL: 'http://localhost:5000/api'
        SOCKET: 'http://localhost:5000'
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: book-lovers-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    environment:
      CONNECTION: ${CONNECTION}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: 'http://localhost:3000'
    restart: unless-stopped
